/**
 * Output formatters: markdown (default) + json (--json).
 *
 * Markdown layout matches the spec sample. Status icons use plain text so
 * the output is readable in non-emoji terminals too.
 *
 * Privacy: we run a redaction pass on any string going into details/fixes/
 * summary, so a stray customer_id in a tool description doesn't leak.
 */

import { REDACTION_KEYS } from '../constants.js';
import type { AuditReport, CheckResult } from '../types.js';

const STATUS_ICON: Record<CheckResult['status'], string> = {
  pass: '[PASS]',
  warn: '[WARN]',
  fail: '[FAIL]'
};

const REDACTION_RE = new RegExp(
  `\\b(${REDACTION_KEYS.map((k) => k.replace(/_/g, '[_-]?')).join('|')})\\b\\s*[:=]\\s*([^\\s,]+)`,
  'gi'
);

function redact(text: string): string {
  return text.replace(REDACTION_RE, (_full, key) => `${key}: [REDACTED]`);
}

function redactAll(items: string[]): string[] {
  return items.map(redact);
}

/** Markdown table-ish output suitable for terminals and PR comments. */
export function renderMarkdown(report: AuditReport): string {
  const lines: string[] = [];
  const versionTag = report.target.version ? ` @${report.target.version}` : '';
  lines.push(`# mcp-scorecard - ${report.target.displayName}${versionTag}`);
  lines.push('');
  lines.push(`**Score: ${report.totalScore}/100 — grade ${report.grade}**  ·  mode: \`${report.mode}\``);
  lines.push('');

  for (const c of report.checks) {
    lines.push(`- ${STATUS_ICON[c.status]} ${c.label.padEnd(28)} (${redact(c.summary)})`);
  }

  // Top fixes: the lowest-scoring checks that have a remediation — biggest points first.
  const top = report.checks
    .filter((c) => c.fixes.length > 0 && c.score < 10)
    .sort((a, b) => a.score - b.score)
    .slice(0, 3);
  if (top.length > 0) {
    lines.push('');
    lines.push('## Top fixes (most points to gain)');
    for (const c of top) {
      lines.push(`- **+${10 - c.score} pts · ${c.label}** — ${redact(c.fixes[0])}`);
    }
  }

  const detailLines: string[] = [];
  for (const c of report.checks) {
    if (c.details.length > 0) {
      detailLines.push(`### ${c.label}`);
      for (const d of redactAll(c.details)) {
        detailLines.push(`- ${d}`);
      }
    }
  }
  if (detailLines.length > 0) {
    lines.push('');
    lines.push('## Details');
    lines.push(...detailLines);
  }

  const fixLines: string[] = [];
  for (const c of report.checks) {
    if (c.fixes.length > 0) {
      for (const f of redactAll(c.fixes)) {
        fixLines.push(`- ${f}`);
      }
    }
  }
  if (fixLines.length > 0) {
    lines.push('');
    lines.push('## Suggested fixes');
    lines.push(...fixLines);
  }

  lines.push('');
  lines.push(`_Generated by mcp-scorecard v${report.scorecardVersion} at ${report.generatedAt}_`);
  return lines.join('\n');
}

/** A shields.io badge (markdown) maintainers can paste into their README. */
export function renderBadge(report: AuditReport): string {
  const color = report.grade === 'A' ? 'brightgreen' : report.grade === 'B' ? 'green'
    : report.grade === 'C' ? 'yellow' : report.grade === 'D' ? 'orange' : 'red';
  const msg = encodeURIComponent(`${report.totalScore}/100 (${report.grade})`);
  const url = `https://img.shields.io/badge/mcp--scorecard-${msg}-${color}`;
  return `[![mcp-scorecard: ${report.grade}](${url})](https://mcp-scorecard.vercel.app)`;
}

/** Side-by-side comparison table for multiple audited targets. */
export function renderCompare(reports: AuditReport[]): string {
  const sorted = [...reports].sort((a, b) => b.totalScore - a.totalScore);
  const lines = ['# mcp-scorecard — comparison', '', '| # | target | score | grade |', '|---|--------|-------|-------|'];
  sorted.forEach((r, i) => {
    lines.push(`| ${i + 1} | ${redact(r.target.displayName)} | ${r.totalScore}/100 | ${r.grade} |`);
  });
  lines.push('', `_Generated by mcp-scorecard v${sorted[0]?.scorecardVersion ?? ''}_`);
  return lines.join('\n');
}

/** Current report + delta against a previous run (regression view). */
export function renderBaseline(report: AuditReport, baseline: AuditReport): string {
  const delta = report.totalScore - baseline.totalScore;
  const arrow = delta > 0 ? `▲ +${delta}` : delta < 0 ? `▼ ${delta}` : '= 0';
  const prevById = new Map(baseline.checks.map((c) => [c.id, c.score]));
  const lines = [renderMarkdown(report), '', '## vs baseline', `**Total: ${report.totalScore}/100 (${arrow} from ${baseline.totalScore})**`, ''];
  for (const c of report.checks) {
    const prev = prevById.get(c.id);
    if (prev !== undefined && prev !== c.score) {
      const d = c.score - prev;
      lines.push(`- ${c.label}: ${prev} → ${c.score} (${d > 0 ? '+' : ''}${d})`);
    }
  }
  return lines.join('\n');
}

/** Self-contained HTML scorecard for sharing / embedding in docs or a PR. */
export function renderHtml(report: AuditReport): string {
  const color = report.grade === 'A' ? '#10b981' : report.grade === 'B' ? '#34d399' : report.grade === 'C' ? '#f59e0b' : report.grade === 'D' ? '#fb923c' : '#f43f5e';
  const esc = (t: string) => t.replace(/[&<>]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[m] as string));
  const rows = report.checks.map((c) => {
    const cc = c.status === 'pass' ? '#10b981' : c.status === 'warn' ? '#f59e0b' : '#f43f5e';
    return `<tr><td>${esc(c.label)}</td><td style="text-align:right;color:${cc};font-weight:700">${c.score}/10</td><td style="color:#9aa6c2">${esc(redact(c.summary))}</td></tr>`;
  }).join('');
  return `<!doctype html><meta charset="utf-8"><title>mcp-scorecard — ${esc(report.target.displayName)}</title>
<div style="font-family:ui-monospace,monospace;background:#0b1120;color:#e8eefc;max-width:760px;margin:30px auto;padding:28px;border-radius:14px">
<div style="font-size:13px;color:#7c8aa6;letter-spacing:.1em">MCP-SCORECARD · ${report.mode.toUpperCase()} MODE</div>
<h1 style="margin:6px 0 2px">${esc(report.target.displayName)}</h1>
<div style="font-size:48px;font-weight:800;color:${color}">${report.totalScore}<span style="font-size:20px;color:#7c8aa6">/100</span> &nbsp;<span style="border:2px solid ${color};border-radius:8px;padding:2px 12px;font-size:24px">${report.grade}</span></div>
<table style="width:100%;border-collapse:collapse;margin-top:18px;font-size:13.5px">${rows}</table>
<p style="color:#7c8aa6;font-size:12px;margin-top:18px">Generated by <a style="color:#10b981" href="https://mcp-scorecard.vercel.app">mcp-scorecard</a> v${report.scorecardVersion} · ${report.generatedAt}</p>
</div>`;
}

export function renderJson(report: AuditReport): string {
  // JSON output is also redacted at the string level so consumers don't
  // accidentally persist secrets from probed servers.
  const redactedChecks = report.checks.map((c) => ({
    ...c,
    summary: redact(c.summary),
    details: redactAll(c.details),
    fixes: redactAll(c.fixes)
  }));
  return JSON.stringify({ ...report, checks: redactedChecks }, null, 2);
}
