/**
 * Output formatters: markdown (default) + json (--json).
 *
 * Markdown layout matches the spec sample. Status icons use plain text so
 * the output is readable in non-emoji terminals too.
 *
 * Privacy: we run a redaction pass on any string going into details/fixes/
 * summary, so a stray customer_id in a tool description doesn't leak.
 */

import { REDACTION_KEYS } from '../constants.js';
import type { AuditReport, CheckResult } from '../types.js';

const STATUS_ICON: Record<CheckResult['status'], string> = {
  pass: '[PASS]',
  warn: '[WARN]',
  fail: '[FAIL]'
};

const REDACTION_RE = new RegExp(
  `\\b(${REDACTION_KEYS.map((k) => k.replace(/_/g, '[_-]?')).join('|')})\\b\\s*[:=]\\s*([^\\s,]+)`,
  'gi'
);

function redact(text: string): string {
  return text.replace(REDACTION_RE, (_full, key) => `${key}: [REDACTED]`);
}

function redactAll(items: string[]): string[] {
  return items.map(redact);
}

/** Markdown table-ish output suitable for terminals and PR comments. */
export function renderMarkdown(report: AuditReport): string {
  const lines: string[] = [];
  const versionTag = report.target.version ? ` @${report.target.version}` : '';
  lines.push(`# mcp-scorecard - ${report.target.displayName}${versionTag}`);
  lines.push('');
  lines.push(`**Agent-readiness score:** ${report.totalScore}/100`);
  lines.push('');

  for (const c of report.checks) {
    lines.push(`- ${STATUS_ICON[c.status]} ${c.label.padEnd(28)} (${redact(c.summary)})`);
  }

  const detailLines: string[] = [];
  for (const c of report.checks) {
    if (c.details.length > 0) {
      detailLines.push(`### ${c.label}`);
      for (const d of redactAll(c.details)) {
        detailLines.push(`- ${d}`);
      }
    }
  }
  if (detailLines.length > 0) {
    lines.push('');
    lines.push('## Details');
    lines.push(...detailLines);
  }

  const fixLines: string[] = [];
  for (const c of report.checks) {
    if (c.fixes.length > 0) {
      for (const f of redactAll(c.fixes)) {
        fixLines.push(`- ${f}`);
      }
    }
  }
  if (fixLines.length > 0) {
    lines.push('');
    lines.push('## Suggested fixes');
    lines.push(...fixLines);
  }

  lines.push('');
  lines.push(`_Generated by mcp-scorecard v${report.scorecardVersion} at ${report.generatedAt}_`);
  return lines.join('\n');
}

export function renderJson(report: AuditReport): string {
  // JSON output is also redacted at the string level so consumers don't
  // accidentally persist secrets from probed servers.
  const redactedChecks = report.checks.map((c) => ({
    ...c,
    summary: redact(c.summary),
    details: redactAll(c.details),
    fixes: redactAll(c.fixes)
  }));
  return JSON.stringify({ ...report, checks: redactedChecks }, null, 2);
}
